#define FOCUS_FRAME "focusFrame"
#define COLOR_ATTACHMENT "colorAttachment" 
#define DEPTH_ATTACHMENT "depthAttachment"
#define COPY_DEPTH_ATTACHMENT "copyDepthAttachment"
#define LAYER_COUNT_TEX "layerCountsTex"
#define DEPTH_DISC_SHADER "depthDiscShader"
#define DEPTH_DISC_TEX "depthDiscTex"
#define MERGING_SHADER "mergingShader"
#define MERGED_FRAG_COUNT "mergedFragCount"
#define FRAG_COLOR_DEPTH_BUFFER "fragColorDepthBuffer"
#define FRAG_MERGING_DATA_BUFFER "fragMergingDataBuffer"
#define TEST_BUFFER "testBuffer"
#define SPLATTING_SHADER "splattingShader"
#define SPLATTED_COLOR_DEPTH_BUFFER "splattedColorDepthBuffer"
#define SPLATTED_FRAG_INFO_BUFFER "splattedFragInfoBuffer"
#define TILING_COUNTER_BUFFER "tilingCounterBuffer"
#define SORTING_SHADER "sortingShader"
#define SORTED_COLOR_DEPTH_BUFFER "sortedColorDepthBuffer"
#define SORTED_FRAG_INFO_BUFFER "sortedFragInfoBuffer"
#define ACCUMULATION_SHADER "accumulationShader"
#define FINAL_IMAGE "finalImage"
#define SCREEN_SHADER "screenShader"
#define SCREEN_QUAD "screenQuad"
#define MAX_FRAGMENT_COUNT 16
#define MAX_FRAGMENT_TILE 8192
#define FLOATING_PERCISION 1000.0f
#define COC_MAX 15
#define SPLAT_WORK_GROUP_SIZE 8
#define DEPTH_DISC_WORK_GROUP_SIZE 32