#define FOCUS_FRAME "focusFrame"
#define MSAA_FOCUS_FRAME "MSAA_FOCUS_FRAME"
#define COLOR_ATTACHMENT "colorAttachment" 
#define MSAA_COLOR_ATTACHMENT "MSAA_COLOR_ATTACHMENT"
#define DEPTH_ATTACHMENT "depthAttachment"
#define MSAA_DEPTH_ATTACHMENT "MSAA_DEPTH_ATTACHMENT"
#define COPY_DEPTH_ATTACHMENT "copyDepthAttachment"
#define LAYER_COUNT_TEX "layerCountsTex"
#define DEPTH_DISC_SHADER "depthDiscShader"
#define DEPTH_DISC_TEX "depthDiscTex"
#define MERGING_SHADER "mergingShader"
#define MERGED_FRAG_COUNT "mergedFragCount"
#define FRAG_COLOR_DEPTH_BUFFER "fragColorDepthBuffer"
#define FRAG_MERGING_DATA_BUFFER "fragMergingDataBuffer"
#define TEST_BUFFER "testBuffer"
#define SPLATTING_SHADER "splattingShader"
#define SPLATTED_COLOR_DEPTH_BUFFER "splattedColorDepthBuffer"
#define SPLATTED_FRAG_INFO_BUFFER "splattedFragInfoBuffer"
#define TILING_COUNTER_BUFFER "tilingCounterBuffer"
#define SORTING_SHADER "sortingShader"
#define SORTED_COLOR_DEPTH_BUFFER "sortedColorDepthBuffer"
#define SORTED_FRAG_INFO_BUFFER "sortedFragInfoBuffer"
#define ACCUMULATION_SHADER "accumulationShader"
#define FINAL_IMAGE "finalImage"
#define SCREEN_SHADER "screenShader"
#define SCREEN_QUAD "screenQuad"
#define MAX_FRAGMENT_COUNT 16
#define MAX_FRAGMENT_TILE 8192
#define FLOATING_PERCISION 100000.0f
#define COC_MAX 32
#define SPLAT_WORK_GROUP_SIZE 8
#define DEPTH_DISC_WORK_GROUP_SIZE 32
#define SCENE_NUM 6
#define AA_SAMPLES 8
#define ENABLE_DOF true
#define SENSOR_WIDTH 0.064
#define RESOLUTION_X 1328
#define RESOLUTION_Y 768
#define ADJACENT_VIEWS glm::uvec2(1, 1)
#define BASELINE 0.042
#define CAMERA_START glm::vec3(-1.32f, -0.105f, -6.0f)
#define CAMERA_END glm::vec3(1.32f, 0.105f, -6.0f)
#define CAMERA_POS glm::vec3(0.042f, 0.042f, -6.0f)
#define CROSS_RENDER false
#define SAMPLE_FULL_PARALLAX_LIGHT_FIELD false
#define SAMPLE_HORIZONTAL_ONLY_PARALLAX_LIGHT_FIELD false
#define STORE_FRAME true
#define STORE_FRAMES false
#define TIME_AVERAGE false
